<?php
$department = $this->getLoadedDepartment(); 
if($this->getConfigListJobs()){
    $postCollection = $this->getLoadedPostsCollection();
    $iterator = 1;
    $total = $jobCollection->count();
} else {
    $total = 0;
}
?>
<?php if($department->getId()) : ?>
    <div class="department-view-wrapper">
        <div class="description"><?php echo $department->getDescription(); ?></div>
    </div>
    <?php if($total): ?>
        <h2><?php echo __('Posts for this department'); ?></h2>
        <?php foreach($postCollection AS $post): ?>
            <ol class="posts list">
                <li class="item<?php echo ($iterator == 1) ? ' first' : ''; ?><?php echo ($total == $iterator) ? ' last' : ''; ?>">
                    <div class="title">
                        <a href="<?php echo $this->getJobUrl($post); ?>" title="<?php echo $post['title']; ?>">
                            <?php echo $post['title']; ?>
                        </a>
                    </div> 
                    <div class="description"><?php echo $post['content']; ?></div>
                </li>
            </ol>
            <?php $iterator++; ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php else : ?>
    <?php echo __('This department does not exist'); ?>
<?php endif; ?>